Repository 9oormthon-univ/2025_SEASONTHON_TEAM_64_BE, pull requests merged in 2025-09, with the labels that each got.

#15 [Feat] 배포 자동화
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/config/SecurityConfig.java
Labels: Feat

#16 [Feat] 배포 자동화
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/security/oauth/handler/Oauth2SuccessHandler.java
Labels: Feat

#17 [Feat] 배포 자동화
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/entity/Member.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/config/SecurityConfig.java
Labels: Feat

#9 [Feat] 게시판 전체 목록 조회 구현
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/comment/repository/CommentRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/FeedSeeder.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/controller/FeedController.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/controller/FeedLikeController.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/controller/dto/request/FeedRequest.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/entity/FeedLike.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/repository/feed/FeedRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/repository/feedLike/FeedLikeJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/repository/feedLike/FeedLikeRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/FeedLikeService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/FeedService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/dto/FeedIdCount.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/dto/response/CursorPageResponse.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/dto/response/FeedLikeResponse.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/dto/response/FeedResponse.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/repository/MemberRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/service/dto/response/MemberResponse.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/common/ErrorCode.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/member/FeedNotFoundException.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/security/oauth/OAuth2KakaoService.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/global/security/jwt/provider/TokenProviderTest.java
Labels: Feat

#22 Feat/#19
  .gitignore
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/FeedSeeder.java
Labels: Fix

#25 [Feat] 회원 정보 반환 기능 구현
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/controller/MemberController.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/service/MemberService.java
Labels: Feat

#30 [Refactor] 포춘쿠키 기능 리팩토링
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/controller/FortuneController.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/controller/dto/request/FortuneCreateRequest.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/entity/Fortune.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/entity/MemberFortune.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/FortuneJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/FortuneRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/fortune/FortuneJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/fortune/FortuneRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/memberfortune/MemberFortuneJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/repository/memberfortune/MemberFortuneRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneAssigner.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneGenerator.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/dto/request/FortuneCreateServiceRequest.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/dto/response/FortuneResponse.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/common/ErrorCode.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/fortune/AlreadyAssignFortuneException.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/fortune/AlreadyGenerateFortuneException.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/global/exception/fortune/FortuneNotFoundException.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/ControllerTestSupport.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/controller/FortuneControllerTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneAssignerTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneGeneratorTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneServiceTest.java
Labels: Refactor, Feat

#32 [Refactor] 알림 기능 리팩토링
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/comment/service/CommentGenerator.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/FeedLikeService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/scheduler/FortuneNotificationScheduler.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/repository/MemberJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/repository/MemberRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/mission/service/MissionAssigner.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/controller/NotificationController.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/entity/Notification.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/event/CommentCreatedEvent.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/event/FeedLikedEvent.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/event/MissionAssignedEvent.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/listener/CommentNotificationListener.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/listener/FeedLikeNotificationListener.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/listener/MissionAssignedNotificationListener.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/push/FcmPushSender.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/push/PushSender.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/repository/NotificationJpaRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/repository/NotificationRepository.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/service/NotificationSenderService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/service/NotificationService.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/service/dto/response/NotificationResponse.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/InMemoryPushSender.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/MulticastRecord.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/SingleRecord.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/TestNotificationConfig.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/comment/service/CommentNotificationTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/feed/service/FeedLikeNotificationTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/fortune/service/FortuneNotificationTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/mission/service/MissionAssignNotificationTest.java
  src/test/java/org/goormthon/seasonthon/nocheongmaru/domain/notification/service/NotificationServiceTest.java
Labels: Refactor, Feat

#35 [Fix] 회원 반환값 Null 오류 해결
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/information/service/InformationReader.java
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/member/service/MemberService.java
Labels: Fix

#36 [Fix] 커서 기반 페이징 쿼리 파람 null 허용으로 변경
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/comment/controller/CommentController.java
Labels: Fix

#42 [Chore] 변수명 변경
  src/main/java/org/goormthon/seasonthon/nocheongmaru/domain/information/controller/InformationController.java
Labels: Chore
